import { swapColorMode, inputToResume, loadPersonalPicture, workExpToResume, educationToResume, preventExcessItems, languageToResume, miscToResume, showDialog, addBulletsOnEnter, addBulletsIfEmpty, changeChkboxLabelText, toggleWorkDescInputs, swapResumeDivs, hideEmptyResumeAreas, changeColorCssVar, changeFontCssVar, printResume, saveResume, loadResume, resumeSpaceObserve, toggleSeparators, toggleResumeBorder } from './events';
import { loadLocalizationData, getLocalizedText, setUserLanguage, swapUserLanguage, getCheckboxText, addSelectOptions, addYearSelectOptions, addMonthSelectOptions } from './localization';
import { setColorMode, addFontOptions } from './utils';
setColorMode();
loadLocalizationData();
setUserLanguage();
const navBarLanguageSwapBtn = document.getElementById('nav-bar-language-button');
navBarLanguageSwapBtn.addEventListener('click', () => (swapUserLanguage()));
navBarLanguageSwapBtn.addEventListener('click', () => (navBarLanguageSwapBtn.innerText = getLocalizedText('nav-bar-language-button')));
navBarLanguageSwapBtn.innerText = getLocalizedText('nav-bar-language-button');
const colorModeBtn = document.getElementById('color-mode-button');
colorModeBtn.addEventListener('click', () => (swapColorMode()));
const navBarHeader = document.getElementById('nav-bar-header');
navBarLanguageSwapBtn.addEventListener('click', () => (navBarHeader.innerText = getLocalizedText('nav-bar-header')));
navBarHeader.innerText = getLocalizedText('nav-bar-header');
const navBarP = document.getElementById('nav-bar-paragraph');
navBarLanguageSwapBtn.addEventListener('click', () => (navBarP.innerText = getLocalizedText('nav-bar-paragraph')));
navBarP.innerText = getLocalizedText('nav-bar-paragraph');
const personalInfoHeader = document.getElementById('personal-info-header');
navBarLanguageSwapBtn.addEventListener('click', () => (personalInfoHeader.innerText = getLocalizedText('personal-info-header')));
personalInfoHeader.innerText = getLocalizedText('personal-info-header');
const nameTipBtn = document.getElementById('personal-name-tip-button');
nameTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('personal-name-tip-button'))));
const nameHeader = document.getElementById('personal-name-header');
const nameInputElement = document.getElementById('personal-name-input');
const nameResumeElement = document.getElementById('personal-name');
nameInputElement.addEventListener('input', () => (inputToResume(nameInputElement, nameResumeElement)));
navBarLanguageSwapBtn.addEventListener('click', () => (nameHeader.innerText = getLocalizedText('personal-name-header')));
nameHeader.innerText = getLocalizedText('personal-name-header');
const emailTipBtn = document.getElementById('contact-mail-tip-button');
emailTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('contact-mail-tip-button'))));
const emailHeader = document.getElementById('contact-mail-header');
const emailInputElement = document.getElementById('contact-mail-input');
const emailResumeElement = document.getElementById('contact-mail');
emailInputElement.addEventListener('input', () => (inputToResume(emailInputElement, emailResumeElement)));
navBarLanguageSwapBtn.addEventListener('click', () => (emailHeader.innerText = getLocalizedText('contact-mail-header')));
emailHeader.innerText = getLocalizedText('contact-mail-header');
const contactNoTipBtn = document.getElementById('contact-number-tip-button');
contactNoTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('contact-number-tip-button'))));
const contactNoHeader = document.getElementById('contact-number-header');
const contactNoInputElement = document.getElementById('contact-number-input');
const contactNoResumeElement = document.getElementById('contact-number');
contactNoInputElement.addEventListener('input', () => (inputToResume(contactNoInputElement, contactNoResumeElement)));
navBarLanguageSwapBtn.addEventListener('click', () => (contactNoHeader.innerText = getLocalizedText('contact-number-header')));
contactNoHeader.innerText = getLocalizedText('contact-number-header');
const locationTipBtn = document.getElementById('personal-location-tip-button');
locationTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('personal-location-tip-button'))));
const locationHeader = document.getElementById('personal-location-header');
const locationInputElement = document.getElementById('personal-location-input');
const locationResumeElement = document.getElementById('personal-location');
locationInputElement.addEventListener('input', () => (inputToResume(locationInputElement, locationResumeElement)));
navBarLanguageSwapBtn.addEventListener('click', () => (locationHeader.innerText = getLocalizedText('personal-location-header')));
locationHeader.innerText = getLocalizedText('personal-location-header');
const linkTipBtn = document.getElementById('custom-link-tip-button');
linkTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('custom-link-tip-button'))));
const linkHeader = document.getElementById('custom-link-header');
const linkInputElement = document.getElementById('custom-link-input');
const linkResumeElement = document.getElementById('custom-link');
linkInputElement.addEventListener('input', () => (inputToResume(linkInputElement, linkResumeElement)));
navBarLanguageSwapBtn.addEventListener('click', () => (linkHeader.innerText = getLocalizedText('custom-link-header')));
linkHeader.innerText = getLocalizedText('custom-link-header');
const personalDescriptionTipBtn = document.getElementById('personal-description-tip-button');
personalDescriptionTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('personal-description-tip-button'))));
const personalDescriptionHeader = document.getElementById('personal-description-header');
navBarLanguageSwapBtn.addEventListener('click', () => (personalDescriptionHeader.innerText = getLocalizedText('personal-description-header')));
personalDescriptionHeader.innerText = getLocalizedText('personal-description-header');
const personalDescriptionInput = document.getElementById('personal-description-input');
const personalDescriptionResumeElement = document.getElementById('personal-description');
personalDescriptionInput.addEventListener('input', () => (inputToResume(personalDescriptionInput, personalDescriptionResumeElement)));
const personalPictureTipBtn = document.getElementById('personal-picture-tip-button');
personalPictureTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('personal-picture-tip-button'))));
const personalPictureHeader = document.getElementById('personal-picture-header');
const personalPictureInput = document.getElementById('personal-picture-input');
const personalPictureLabel = document.getElementById('personal-picture-label');
personalPictureInput.addEventListener('change', () => (loadPersonalPicture(personalPictureInput.files)));
navBarLanguageSwapBtn.addEventListener('click', () => (personalPictureLabel.innerText = getLocalizedText('personal-picture-label')));
navBarLanguageSwapBtn.addEventListener('click', () => (personalPictureHeader.innerText = getLocalizedText('personal-picture-header')));
personalPictureHeader.innerText = getLocalizedText('personal-picture-header');
personalPictureLabel.innerText = getLocalizedText('personal-picture-label');
const workExpHeader = document.getElementById('work-experience-header');
navBarLanguageSwapBtn.addEventListener('click', () => (workExpHeader.innerText = getLocalizedText('work-experience-header')));
workExpHeader.innerText = getLocalizedText('work-experience-header');
const companyNameHeader = document.getElementById('work-company-header');
navBarLanguageSwapBtn.addEventListener('click', () => (companyNameHeader.innerText = getLocalizedText('work-company-header')));
companyNameHeader.innerText = getLocalizedText('work-company-header');
const companyNameTipBtn = document.getElementById('work-company-tip-button');
companyNameTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('work-company-tip-button'))));
const workPosHeader = document.getElementById('work-position-header');
navBarLanguageSwapBtn.addEventListener('click', () => (workPosHeader.innerText = getLocalizedText('work-position-header')));
workPosHeader.innerText = getLocalizedText('work-position-header');
const workPosTipBtn = document.getElementById('work-position-tip-button');
workPosTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('work-position-tip-button'))));
const workStrHeader = document.getElementById('work-start-header');
navBarLanguageSwapBtn.addEventListener('click', () => (workStrHeader.innerText = getLocalizedText('start-date-header')));
workStrHeader.innerText = getLocalizedText('start-date-header');
const workEndHeader = document.getElementById('work-end-header');
navBarLanguageSwapBtn.addEventListener('click', () => (workEndHeader.innerText = getLocalizedText('end-date-header')));
workEndHeader.innerText = getLocalizedText('end-date-header');
const workDescBulletHeader = document.getElementById('work-experience-bullets-header');
navBarLanguageSwapBtn.addEventListener('click', () => (workDescBulletHeader.innerText = getLocalizedText('work-experience-bullets-header')));
workDescBulletHeader.innerText = getLocalizedText('work-experience-bullets-header');
const workDescBulletTipBtn = document.getElementById('work-experience-bullets-tip-button');
workDescBulletTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('work-experience-bullets-tip-button'))));
const workDescHeader = document.getElementById('work-description-header');
navBarLanguageSwapBtn.addEventListener('click', () => (workDescHeader.innerText = getLocalizedText('work-description-header')));
workDescHeader.innerText = getLocalizedText('work-description-header');
const workDescTipBtn = document.getElementById('work-description-tip-button');
workDescTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('work-description-tip-button'))));
const companyNameInput = document.getElementById('work-company-input');
const workPosInput = document.getElementById('work-position-input');
const workDescInput = document.getElementById('work-description-input');
const workDescTextArea = document.getElementById('work-description-text-area');
const workDescBulletToggleCheckbox = document.getElementById('work-experience-bullets-checkbox');
const workDescBulletToggleCheckboxLabel = document.getElementById('work-experience-bullets-checkbox-label');
const workDescBulletSelect = document.getElementById('work-experience-bullets-select');
const workStrMthSelect = document.getElementById('work-start-month-input');
const workStrYrSelect = document.getElementById('work-start-year-input');
const workEndMthSelect = document.getElementById('work-end-month-input');
const workEndYrSelect = document.getElementById('work-end-year-input');
const workPresentCheckbox = document.getElementById('work-present-checkbox');
const workPresentCheckboxLabel = document.getElementById('work-present-checkbox-label');
const workItemsList = document.getElementById('experience-items-container');
const resumeExpList = document.getElementById('work-experience-resume-container');
const workExpItemsBtn = document.getElementById('add-experience-button');
const workAreaMsgSpan = document.getElementById('work-experience-message-span');
workDescBulletToggleCheckbox.addEventListener('click', () => (toggleWorkDescInputs(workDescBulletToggleCheckbox, workDescInput, workDescTextArea, workDescBulletSelect)));
workDescBulletToggleCheckbox.addEventListener('click', () => (changeChkboxLabelText(workDescBulletToggleCheckbox, workDescBulletToggleCheckboxLabel, 'work-experience-bullets-label-checked', 'work-experience-bullets-label')));
workDescTextArea.addEventListener('keyup', (event) => (addBulletsOnEnter(event, workDescTextArea, workDescBulletSelect)));
workDescTextArea.addEventListener('focus', () => (addBulletsIfEmpty(workDescTextArea, workDescBulletSelect)));
workExpItemsBtn.addEventListener('click', () => (workExpToResume(companyNameInput, workPosInput, workDescInput, workDescTextArea, workStrMthSelect, workStrYrSelect, workEndMthSelect, workEndYrSelect, workPresentCheckbox, workItemsList, resumeExpList, workAreaMsgSpan)));
preventExcessItems(workItemsList, workExpItemsBtn, 10, 'max-items-msg', resumeExpList);
addMonthSelectOptions(workStrMthSelect);
addMonthSelectOptions(workEndMthSelect);
addYearSelectOptions(workStrYrSelect);
addYearSelectOptions(workEndYrSelect);
navBarLanguageSwapBtn.addEventListener('click', () => (addMonthSelectOptions(workStrMthSelect)));
navBarLanguageSwapBtn.addEventListener('click', () => (addMonthSelectOptions(workEndMthSelect)));
navBarLanguageSwapBtn.addEventListener('click', () => (workDescBulletToggleCheckboxLabel.innerText = getCheckboxText(workDescBulletToggleCheckbox, 'work-experience-bullets-label-checked', 'work-experience-bullets-label')));
workDescBulletToggleCheckboxLabel.innerText = getCheckboxText(workDescBulletToggleCheckbox, 'work-experience-bullets-label-checked', 'work-experience-bullets-label');
navBarLanguageSwapBtn.addEventListener('click', () => (workPresentCheckboxLabel.innerText = getLocalizedText('present-date')));
workPresentCheckboxLabel.innerText = getLocalizedText('present-date');
navBarLanguageSwapBtn.addEventListener('click', () => (workExpItemsBtn.innerText = getLocalizedText('add-experience-button')));
workExpItemsBtn.innerText = getLocalizedText('add-experience-button');
const educationHeader = document.getElementById('education-header');
navBarLanguageSwapBtn.addEventListener('click', () => (educationHeader.innerText = getLocalizedText('education-header')));
educationHeader.innerText = getLocalizedText('education-header');
const educationGradeHeader = document.getElementById('education-grade-header');
navBarLanguageSwapBtn.addEventListener('click', () => (educationGradeHeader.innerText = getLocalizedText('education-grade-header')));
educationGradeHeader.innerText = getLocalizedText('education-grade-header');
const educationTitleHeader = document.getElementById('education-title-header');
navBarLanguageSwapBtn.addEventListener('click', () => (educationTitleHeader.innerText = getLocalizedText('education-title-header')));
educationTitleHeader.innerText = getLocalizedText('education-title-header');
const educationInstitutionHeader = document.getElementById('education-institution-header');
navBarLanguageSwapBtn.addEventListener('click', () => (educationInstitutionHeader.innerText = getLocalizedText('education-institution-header')));
educationInstitutionHeader.innerText = getLocalizedText('education-institution-header');
const educationStrHeader = document.getElementById('education-start-header');
navBarLanguageSwapBtn.addEventListener('click', () => (educationStrHeader.innerText = getLocalizedText('start-date-header')));
educationStrHeader.innerText = getLocalizedText('start-date-header');
const educationEndHeader = document.getElementById('education-end-header');
navBarLanguageSwapBtn.addEventListener('click', () => (educationEndHeader.innerText = getLocalizedText('end-date-header')));
educationEndHeader.innerText = getLocalizedText('end-date-header');
const educationGradeSelect = document.getElementById('education-grade-select');
const educationTitleInput = document.getElementById('education-title-input');
const educationInstitutionInput = document.getElementById('education-institution-input');
const educationStrMthSelect = document.getElementById('education-start-month-input');
const educationStrYrSelect = document.getElementById('education-start-year-input');
const educationEndMthSelect = document.getElementById('education-end-month-input');
const educationEndYrSelect = document.getElementById('education-end-year-input');
const educationPresentCheckbox = document.getElementById('education-present-checkbox');
const educationPresentCheckboxLabel = document.getElementById('education-present-checkbox-label');
const educationItemsList = document.getElementById('education-items-container');
const resumeEdList = document.getElementById('education-resume-container');
const educationItemsBtn = document.getElementById('add-education-button');
const educationAreaMsgSpan = document.getElementById('education-message-span');
educationItemsBtn.addEventListener('click', () => (educationToResume(educationTitleInput, educationGradeSelect, educationInstitutionInput, educationStrMthSelect, educationStrYrSelect, educationEndMthSelect, educationEndYrSelect, educationPresentCheckbox, educationItemsList, resumeEdList, educationAreaMsgSpan)));
preventExcessItems(educationItemsList, educationItemsBtn, 10, 'max-items-msg', resumeEdList);
addSelectOptions(educationGradeSelect, 'education-grade-select-options');
addMonthSelectOptions(educationStrMthSelect);
addMonthSelectOptions(educationEndMthSelect);
addYearSelectOptions(educationStrYrSelect);
addYearSelectOptions(educationEndYrSelect);
navBarLanguageSwapBtn.addEventListener('click', () => (addSelectOptions(educationGradeSelect, 'education-grade-select-options')));
navBarLanguageSwapBtn.addEventListener('click', () => (addMonthSelectOptions(educationStrMthSelect)));
navBarLanguageSwapBtn.addEventListener('click', () => (addMonthSelectOptions(educationEndMthSelect)));
navBarLanguageSwapBtn.addEventListener('click', () => (educationPresentCheckboxLabel.innerText = getLocalizedText('present-date')));
educationPresentCheckboxLabel.innerText = getLocalizedText('present-date');
navBarLanguageSwapBtn.addEventListener('click', () => (educationItemsBtn.innerText = getLocalizedText('add-education-button')));
educationItemsBtn.innerText = getLocalizedText('add-education-button');
const educationOrderTipBtn = document.getElementById('education-order-tip-button');
educationOrderTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('education-order-tip-button'))));
const educationOrderCheckbox = document.getElementById('education-order-checkbox');
const educationOrderCheckboxLabel = document.getElementById('education-order-checkbox-label');
const workExpResumeDiv = document.getElementById('work-experience-resume-div');
const educationResumeDiv = document.getElementById('education-resume-div');
educationOrderCheckbox.addEventListener('click', () => (swapResumeDivs(workExpResumeDiv, educationResumeDiv)));
educationOrderCheckbox.addEventListener('click', () => (changeChkboxLabelText(educationOrderCheckbox, educationOrderCheckboxLabel, 'prioritize-experience', 'prioritize-education')));
hideEmptyResumeAreas(workItemsList, workExpResumeDiv);
hideEmptyResumeAreas(educationItemsList, educationResumeDiv);
navBarLanguageSwapBtn.addEventListener('click', () => (educationOrderCheckboxLabel.innerText = getCheckboxText(educationOrderCheckbox, 'prioritize-experience', 'prioritize-education')));
educationOrderCheckboxLabel.innerText = getCheckboxText(educationOrderCheckbox, 'prioritize-experience', 'prioritize-education');
const languageHeader = document.getElementById('language-header');
navBarLanguageSwapBtn.addEventListener('click', () => (languageHeader.innerText = getLocalizedText('language-header')));
languageHeader.innerText = getLocalizedText('language-header');
const languageTipBtn = document.getElementById('language-tip-button');
languageTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('language-tip-button'))));
const languageNameHeader = document.getElementById('language-name-header');
navBarLanguageSwapBtn.addEventListener('click', () => (languageNameHeader.innerText = getLocalizedText('language-name-header')));
languageNameHeader.innerText = getLocalizedText('language-name-header');
const languageLevelHeader = document.getElementById('language-level-header');
navBarLanguageSwapBtn.addEventListener('click', () => (languageLevelHeader.innerText = getLocalizedText('language-level-header')));
languageLevelHeader.innerText = getLocalizedText('language-level-header');
const languageNameInput = document.getElementById('language-name-input');
const languageLevelSelect = document.getElementById('language-level-select');
const languageItemsDiv = document.getElementById('language-items-container');
const resumeLanguageDiv = document.getElementById('language-resume-container');
const languageItemsBtn = document.getElementById('add-language-button');
const languageAreaMsgSpan = document.getElementById('language-message-span');
addSelectOptions(languageLevelSelect, 'language-level-select-options');
hideEmptyResumeAreas(languageItemsDiv, resumeLanguageDiv);
languageItemsBtn.addEventListener('click', () => (languageToResume(languageNameInput, languageLevelSelect, languageItemsDiv, resumeLanguageDiv, languageAreaMsgSpan)));
navBarLanguageSwapBtn.addEventListener('click', () => (addSelectOptions(languageLevelSelect, 'language-level-select-options')));
navBarLanguageSwapBtn.addEventListener('click', () => (languageItemsBtn.innerText = getLocalizedText('add-language-button')));
languageItemsBtn.innerText = getLocalizedText('add-language-button');
const miscHeader = document.getElementById('miscellaneous-header');
navBarLanguageSwapBtn.addEventListener('click', () => (miscHeader.innerText = getLocalizedText('miscellaneous-header')));
miscHeader.innerText = getLocalizedText('miscellaneous-header');
const miscSkillsHeader = document.getElementById('miscellaneous-skills-header');
navBarLanguageSwapBtn.addEventListener('click', () => (miscSkillsHeader.innerText = getLocalizedText('miscellaneous-skills-header')));
miscSkillsHeader.innerText = getLocalizedText('miscellaneous-skills-header');
const miscSkillsTipBtn = document.getElementById('miscellaneous-skills-tip-button');
miscSkillsTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('miscellaneous-skills-tip-button'))));
const miscSkillsInput = document.getElementById('miscellaneous-skills-input');
const miscSkillsItemsDiv = document.getElementById('miscellaneous-skills-container');
const resumeMiscSkillsDiv = document.getElementById('miscellaneous-skills-resume-container');
const miscSkillsItemsBtn = document.getElementById('add-miscellaneous-skill-button');
const miscSkillsAreaMsgSpan = document.getElementById('miscellaneous-skills-message-span');
miscSkillsItemsBtn.addEventListener('click', () => (miscToResume(miscSkillsInput, miscSkillsItemsDiv, resumeMiscSkillsDiv, miscSkillsAreaMsgSpan)));
hideEmptyResumeAreas(miscSkillsItemsDiv, resumeMiscSkillsDiv);
navBarLanguageSwapBtn.addEventListener('click', () => (miscSkillsItemsBtn.innerText = getLocalizedText('add-miscellaneous-skill-button')));
miscSkillsItemsBtn.innerText = getLocalizedText('add-miscellaneous-skill-button');
const miscQltyHeader = document.getElementById('miscellaneous-qualities-header');
navBarLanguageSwapBtn.addEventListener('click', () => (miscQltyHeader.innerText = getLocalizedText('miscellaneous-qualities-header')));
miscQltyHeader.innerText = getLocalizedText('miscellaneous-qualities-header');
const miscQltyTipBtn = document.getElementById('miscellaneous-qualities-tip-button');
miscQltyTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('miscellaneous-qualities-tip-button'))));
const miscQltyInput = document.getElementById('miscellaneous-qualities-input');
const miscQltyItemsDiv = document.getElementById('miscellaneous-qualities-container');
const resumeMiscQltyDiv = document.getElementById('miscellaneous-qualities-resume-container');
const miscQltyItemsBtn = document.getElementById('add-miscellaneous-qualities-button');
const miscQltyAreaMsgSpan = document.getElementById('miscellaneous-qualities-message-span');
miscQltyItemsBtn.addEventListener('click', () => (miscToResume(miscQltyInput, miscQltyItemsDiv, resumeMiscQltyDiv, miscQltyAreaMsgSpan)));
hideEmptyResumeAreas(miscQltyItemsDiv, resumeMiscQltyDiv);
navBarLanguageSwapBtn.addEventListener('click', () => (miscQltyItemsBtn.innerText = getLocalizedText('add-miscellaneous-qualities-button')));
miscQltyItemsBtn.innerText = getLocalizedText('add-miscellaneous-qualities-button');
const miscIntrstHeader = document.getElementById('miscellaneous-interests-header');
navBarLanguageSwapBtn.addEventListener('click', () => (miscIntrstHeader.innerText = getLocalizedText('miscellaneous-interests-header')));
miscIntrstHeader.innerText = getLocalizedText('miscellaneous-interests-header');
const miscIntrstTipBtn = document.getElementById('miscellaneous-interests-tip-button');
miscIntrstTipBtn.addEventListener('click', () => (showDialog(getLocalizedText('miscellaneous-interests-tip-button'))));
const miscIntrstInput = document.getElementById('miscellaneous-interests-input');
const miscIntrstItemsDiv = document.getElementById('miscellaneous-interests-container');
const resumeMiscIntrstDiv = document.getElementById('miscellaneous-interests-resume-container');
const miscIntrstItemsBtn = document.getElementById('add-miscellaneous-interests-button');
const miscIntrstAreaMsgSpan = document.getElementById('miscellaneous-interests-message-span');
miscIntrstItemsBtn.addEventListener('click', () => (miscToResume(miscIntrstInput, miscIntrstItemsDiv, resumeMiscIntrstDiv, miscIntrstAreaMsgSpan)));
hideEmptyResumeAreas(miscIntrstItemsDiv, resumeMiscIntrstDiv);
navBarLanguageSwapBtn.addEventListener('click', () => (miscIntrstItemsBtn.innerText = getLocalizedText('add-miscellaneous-interests-button')));
miscIntrstItemsBtn.innerText = getLocalizedText('add-miscellaneous-interests-button');
const workExpResumeHeader = document.getElementById('work-experience-resume-header');
navBarLanguageSwapBtn.addEventListener('click', () => (workExpResumeHeader.innerText = getLocalizedText('work-experience-header')));
workExpResumeHeader.innerText = getLocalizedText('work-experience-header');
const educationResumeHeader = document.getElementById('education-resume-header');
navBarLanguageSwapBtn.addEventListener('click', () => (educationResumeHeader.innerText = getLocalizedText('education-header')));
educationResumeHeader.innerText = getLocalizedText('education-header');
const languageResumeHeader = document.getElementById('language-resume-header');
navBarLanguageSwapBtn.addEventListener('click', () => (languageResumeHeader.innerText = getLocalizedText('language-header')));
languageResumeHeader.innerText = getLocalizedText('language-header');
const miscSkillsResumeHeader = document.getElementById('miscellaneous-skills-resume-header');
navBarLanguageSwapBtn.addEventListener('click', () => (miscSkillsResumeHeader.innerText = getLocalizedText('miscellaneous-skills-header')));
miscSkillsResumeHeader.innerText = getLocalizedText('miscellaneous-skills-header');
const miscQltyResumeHeader = document.getElementById('miscellaneous-qualities-resume-header');
navBarLanguageSwapBtn.addEventListener('click', () => (miscQltyResumeHeader.innerText = getLocalizedText('miscellaneous-qualities-header')));
miscQltyResumeHeader.innerText = getLocalizedText('miscellaneous-qualities-header');
const miscIntrstResumeHeader = document.getElementById('miscellaneous-interests-resume-header');
navBarLanguageSwapBtn.addEventListener('click', () => (miscIntrstResumeHeader.innerText = getLocalizedText('miscellaneous-interests-header')));
miscIntrstResumeHeader.innerText = getLocalizedText('miscellaneous-interests-header');
const printResumeBtn = document.getElementById('print-resume-button');
const resumeContainer = document.getElementById('resume-div');
printResumeBtn.addEventListener('click', () => (printResume(resumeContainer)));
navBarLanguageSwapBtn.addEventListener('click', () => (printResumeBtn.innerText = getLocalizedText('print-resume-button')));
printResumeBtn.innerText = getLocalizedText('print-resume-button');
const saveResumeBtn = document.getElementById('save-resume-button');
saveResumeBtn.addEventListener('click', () => (saveResume()));
navBarLanguageSwapBtn.addEventListener('click', () => (saveResumeBtn.innerText = getLocalizedText('save-resume-button')));
saveResumeBtn.innerText = getLocalizedText('save-resume-button');
const loadResumeInput = document.getElementById('load-resume-input');
const loadResumeLabel = document.getElementById('load-resume-label');
loadResumeLabel.addEventListener('click', () => (showDialog(getLocalizedText('import-msg'))));
loadResumeInput.addEventListener('change', () => loadResume(loadResumeInput.files));
navBarLanguageSwapBtn.addEventListener('click', () => (loadResumeLabel.innerText = getLocalizedText('load-resume-button')));
loadResumeLabel.innerText = getLocalizedText('load-resume-button');
resumeSpaceObserve();
const customizationHeader = document.getElementById('customization-header');
navBarLanguageSwapBtn.addEventListener('click', () => (customizationHeader.innerText = getLocalizedText('customization-header')));
customizationHeader.innerText = getLocalizedText('customization-header');
const customHeaderColorHeader = document.getElementById('custom-header-color-header');
navBarLanguageSwapBtn.addEventListener('click', () => (customHeaderColorHeader.innerText = getLocalizedText('custom-header-color-header')));
customHeaderColorHeader.innerText = getLocalizedText('custom-header-color-header');
const customHeaderColorSelect = document.getElementById('custom-header-color-select');
customHeaderColorSelect.addEventListener('change', () => (changeColorCssVar(customHeaderColorSelect, '--resume-headers-color')));
navBarLanguageSwapBtn.addEventListener('click', () => (addSelectOptions(customHeaderColorSelect, 'color-select-options')));
addSelectOptions(customHeaderColorSelect, 'color-select-options');
const customFontSizeHeader = document.getElementById('custom-font-size-header');
navBarLanguageSwapBtn.addEventListener('click', () => (customFontSizeHeader.innerText = getLocalizedText('custom-font-size-header')));
customFontSizeHeader.innerText = getLocalizedText('custom-font-size-header');
const customFontSizeSelect = document.getElementById('custom-font-size');
customFontSizeSelect.addEventListener('change', () => (changeFontCssVar(customFontSizeSelect, '--resume-font-size')));
const customNameFontHeader = document.getElementById('custom-name-font-header');
navBarLanguageSwapBtn.addEventListener('click', () => (customNameFontHeader.innerText = getLocalizedText('custom-name-font-header')));
customNameFontHeader.innerText = getLocalizedText('custom-name-font-header');
const customNameFontSelect = document.getElementById('custom-name-font');
customNameFontSelect.addEventListener('change', () => (changeFontCssVar(customNameFontSelect, '--resume-name-font')));
addFontOptions(customNameFontSelect);
const customSectionHeaderFontHeader = document.getElementById('custom-section-header-font-header');
navBarLanguageSwapBtn.addEventListener('click', () => (customSectionHeaderFontHeader.innerText = getLocalizedText('custom-section-header-font-header')));
customSectionHeaderFontHeader.innerText = getLocalizedText('custom-section-header-font-header');
const customSectionHeaderFontSelect = document.getElementById('custom-section-header-font');
customSectionHeaderFontSelect.addEventListener('change', () => (changeFontCssVar(customSectionHeaderFontSelect, '--resume-section-header-font')));
addFontOptions(customSectionHeaderFontSelect);
const customHeaderFontHeader = document.getElementById('custom-header-font-header');
navBarLanguageSwapBtn.addEventListener('click', () => (customHeaderFontHeader.innerText = getLocalizedText('custom-header-font-header')));
customHeaderFontHeader.innerText = getLocalizedText('custom-header-font-header');
const customHeaderFontSelect = document.getElementById('custom-header-font');
customHeaderFontSelect.addEventListener('change', () => (changeFontCssVar(customHeaderFontSelect, '--resume-big-header-font')));
addFontOptions(customHeaderFontSelect);
const customTextFontHeader = document.getElementById('custom-text-font-header');
navBarLanguageSwapBtn.addEventListener('click', () => (customTextFontHeader.innerText = getLocalizedText('custom-text-font-header')));
customTextFontHeader.innerText = getLocalizedText('custom-text-font-header');
const customTextFontSelect = document.getElementById('custom-text-font');
customTextFontSelect.addEventListener('change', () => (changeFontCssVar(customTextFontSelect, '--resume-text-font')));
addFontOptions(customTextFontSelect);
const separatorHeader = document.getElementById('separator-header');
navBarLanguageSwapBtn.addEventListener('click', () => (separatorHeader.innerText = getLocalizedText('separator-header')));
separatorHeader.innerText = getLocalizedText('separator-header');
const separatorCheckbox = document.getElementById('separator-input');
const separatorLabel = document.getElementById('separator-label');
separatorLabel.addEventListener('click', () => (toggleSeparators(separatorCheckbox)));
navBarLanguageSwapBtn.addEventListener('click', () => (separatorLabel.innerText = getLocalizedText('separator-label')));
separatorLabel.innerText = getLocalizedText('separator-label');
const separatorColorHeader = document.getElementById('separator-color-header');
navBarLanguageSwapBtn.addEventListener('click', () => (separatorColorHeader.innerText = getLocalizedText('separator-color-header')));
separatorColorHeader.innerText = getLocalizedText('separator-color-header');
const separatorColorSelect = document.getElementById('separator-color-select');
separatorColorSelect.addEventListener('change', () => (changeColorCssVar(separatorColorSelect, '--resume-separator-color')));
navBarLanguageSwapBtn.addEventListener('click', () => (addSelectOptions(separatorColorSelect, 'color-select-options')));
addSelectOptions(separatorColorSelect, 'color-select-options');
const resumeBorderHeader = document.getElementById('resume-border-header');
navBarLanguageSwapBtn.addEventListener('click', () => (resumeBorderHeader.innerText = getLocalizedText('resume-border-header')));
resumeBorderHeader.innerText = getLocalizedText('resume-border-header');
const resumeBorderCheckbox = document.getElementById('resume-border-input');
const resumeBorderLabel = document.getElementById('resume-border-label');
resumeBorderLabel.addEventListener('click', () => (toggleResumeBorder(resumeBorderCheckbox)));
navBarLanguageSwapBtn.addEventListener('click', () => (resumeBorderLabel.innerText = getLocalizedText('resume-border-label')));
resumeBorderLabel.innerText = getLocalizedText('resume-border-label');
const resumeBorderColorHeader = document.getElementById('resume-border-color-header');
navBarLanguageSwapBtn.addEventListener('click', () => (resumeBorderColorHeader.innerText = getLocalizedText('resume-border-color-header')));
resumeBorderColorHeader.innerText = getLocalizedText('resume-border-color-header');
const resumeBorderColorSelect = document.getElementById('resume-border-color-select');
resumeBorderColorSelect.addEventListener('change', () => (changeColorCssVar(resumeBorderColorSelect, '--resume-border-color')));
navBarLanguageSwapBtn.addEventListener('click', () => (addSelectOptions(resumeBorderColorSelect, 'color-select-options')));
addSelectOptions(resumeBorderColorSelect, 'color-select-options');
